
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          run: 'npm install'
          build: 'npm run build'  # run a custom app build step
       # run on 2 machines using Chrome browser
      - cypress/run:
          name: '2 machines using Chrome'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome76
          # use browser "chrome" for running tests
          browser: chrome
          record: true
          parallel: true
          parallelism: 2
          group: '2x-chrome on CircleCI'
          start: 'npm run start:ci'
