name: Node.js CI

on:
  pull_request:
    branches:
      - testing_ci
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        ci_node_total: [3]
        ci_node_index: [0,1,2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        record: true
        parallel: true
    - run: npm install
    - run: npm run build --if-present 
    - run: npm run test
      
        

                   
 
