- name: Install Cypress and dependencies
  uses: cypress-io/github-action@v1
  with:
    runTests: false

# quickly run just the changed specs to fail fast
- name: Maybe run just the changed Cypress tests ⏱
  run: |
    CHANGED_SPECS=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- cypress/integration)
    if [ -n "$CHANGED_SPECS" ]; then
      echo "Running the following changed specs"
      echo $CHANGED_SPECS
      npx cypress run --spec $CHANGED_SPECS
    fi

- name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        containers: [1, 2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        record: true
        parallel: true
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
