name: Node.js CI

on:
  push:
    branches:
      - testing_ci
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        machines: [1, 2, 3]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        record: true
        parallel: true
        parallelism: 4
    
    - run: npm install
    - run: npm run build --if-present 
    - run: npm run test
      
        

                   
 
