name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [3]
        ci_node_index: [0, 1, 2]

    steps:
 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        record: true
        parallel: true
        group: 'test qa'
    - run: npm install
    - run: npm run build --if-present
    - run: npx cypress run --parallel --record --key ebfde98d-2fc7-4d17-b2e9-e18e66ffd7f3
    - name: Extract branch name
      shell: bash
    - run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Test
      run: echo "${BRANCH_NAME}"
