name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - id: file_changes
      - uses: trilom/file-changes-action@v1.2.3
      - run: npm install
      - run: npm run build --if-present 
      - run: npm run test


                   
 
